services:
  postgres:
    image: postgres:15
    container_name: supermarket_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

mongo:
  image: mongo:6
  container_name: supermarket_mongo
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  ports:
    - "27020: 27017"
  volumes:
    - mongo_data:/data/db
  networks:
    - etl_network
      